### ISSUE TITLE
[docs] Create Checklist for Releasing Android App to Google's Play Store

### ISSUE THREAD

**Issue by sidharthshah** [fafadiatech/newscout_android#33]

**Comment by sidharthshah** [comment]
@gmcodebuster please also include section on how to Deploy Builds using `Firebase` as `Crashlytics` is not working anymore.

**Comment by gmcodebuster** [comment]
[Android_Checklist_PlayStore_Upload (copy).txt](https://github.com/fafadiatech/newscout_android/files/4409607/Android_Checklist_PlayStore_Upload.copy.txt)
