### ISSUE TITLE
[bug] app crashing on daily digest 

### ISSUE THREAD

**Issue by Shivani-Padhye** [fafadiatech/newscout_android#37]
step to reproduce -
1.go to newscout app
2.you will see that data is not rendering and after 3-4 minutes the app will crash.

**Comment by gmcodebuster** [comment]
check below link for report
https://fabric.io/fafadiatech2/android/apps/com.fafadiatech.newscout/issues/35fa1909f7b688f5bab366abce09020a/sessions/latest

**Comment by Shivani-Padhye** [comment]
Tested in version 1.0.9.7. now app is not crashing, working smoothly.
