### ISSUE TITLE
[enhancement] Make ads items a little more expliticit

### ISSUE THREAD

**Issue by sidharthshah** [fafadiatech/newscout_android#7]
Show "Promoted" with small icon like how it happens in Twitter. This will help user differentiate between regular news items and promoted news item.

[Reference](https://blog.hootsuite.com/twitter-ads/)

**Comment by Shivani-Padhye** [comment]
unable to find ads in the app.

**Comment by Shivani-Padhye** [comment]
only keyword is visible in ad card. and icon is missing
![Screenshot_20200414-120029_NewScout](https://user-images.githubusercontent.com/57176686/79193287-f23bbb00-7e47-11ea-888f-6c76fcb74a53.jpg)

**Comment by gmcodebuster** [comment]
@Shivani-Padhye  screen shot of ads view with icons

![Screenshot_20200415-112400](https://user-images.githubusercontent.com/4159259/79303352-4f994000-7f0c-11ea-9639-c28a0a917e7c.png)
![Screenshot_20200415-112519](https://user-images.githubusercontent.com/4159259/79303398-70619580-7f0c-11ea-9fb2-22751cb203ad.png)
